build-image: &build-image
  machine: true
  steps:
    - checkout
    - run:
      name: Docker login
      command: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - run:
      name: test docker
      command: docker ps
    - run:
      name: build image
      command: docker build . -t eugenmayer/java:server-jre8

version: 2        
jobs:
   build: 
     <<: *build-image
   deploy:
     <<: *build-image
     steps:
       - run:
         name: deploying
         command: echo deployed
   
workflows:
  version: 2
  jobs:
    - build:
      filters:
        branches:
          only:
            - master
    - hold:
      type: approval
      requires:
        - build
    - deploy:
      requires:
       - hold
      filters:
        tags:
          only: /^v*/
