version: 2
jobs:
  build:
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: test docker
          command: docker ps
      - run:
          name: build image
          command: docker build . eugenmayer/java:server-jre8

